# Set up TensorFlow

In [3]:
# imports
import tensorflow as tf
print("TensorFlow version:",  tf.__version__)

TensorFlow version: 2.7.0


# Load  a dataset

In [5]:
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [8]:
print(len(x_train), len(x_test), len(y_train), len(y_test))

60000 10000 60000 10000


# Building Machine Learning Model

In [13]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])


In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [15]:
x_train.shape

(60000, 28, 28)

In [18]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 2.27038422e+02, -3.72488632e+01, -1.24708176e-01,
        -1.07117012e+02, -7.37340088e+01, -2.97840729e+01,
         2.27383957e+01,  3.65426445e+00, -1.29834320e+02,
        -2.44850311e+02]], dtype=float32)

In [19]:
tf.nn.softmax(predictions).numpy()

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

# loss functions

In [20]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [24]:
loss_fn(y_train[:1], predictions).numpy()

256.8225

# compile model

In [26]:
# comile mode

In [27]:
model.compile(optimizer='adam',
              loss = loss_fn,
              metrics= ['accuracy'])

# train and evaluate the model

In [31]:
model.fit(x_train, y_train, epochs = 20)

Epoch 1/20
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3135 - accuracy: 0.9215
Epoch 2/20
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3098 - accuracy: 0.9232
Epoch 3/20
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3132 - accuracy: 0.9228
Epoch 4/20
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3083 - accuracy: 0.9229
Epoch 5/20
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2944 - accuracy: 0.9262
Epoch 6/20
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3020 - accuracy: 0.9257
Epoch 7/20
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2961 - accuracy: 0.9290
Epoch 8/20
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2879 - accuracy: 0.9291
Epoch 9/20
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2971 - accuracy: 0.9279
Epoch 10/20
1875/1875 [==============================] - 4s 2ms/step - loss: 0.285

In [34]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.4236 - accuracy: 0.9480 - 520ms/epoch - 2ms/step


[0.42356622219085693, 0.9480000138282776]

In [33]:
# probability model
probability_model = tf.keras.Sequential([
                                         model,
                                         tf.keras.layers.Softmax()
])

In [35]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.0000000e+00, 2.3032762e-28, 1.2306520e-19, 3.5481465e-24,
        2.8934643e-37, 3.2091601e-35, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 7.9662356e-27],
       [0.0000000e+00, 8.3565791e-33, 1.0000000e+00, 1.1066204e-30,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.0352565e-31,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 9.9542419e-33, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 6.6279303e-15, 2.6874015e-38,
        6.6716948e-28, 1.6761569e-20, 2.6696539e-15, 8.0279606e-17,
        0.0000000e+00, 1.9590490e-29],
       [7.8912899e-26, 3.8846602e-17, 1.6158068e-17, 2.3509378e-19,
        9.9999988e-01, 4.7988169e-10, 1.4860458e-21, 1.0444956e-21,
        5.5032884e-21, 9.7478782e-08]], dtype=float32)>